### ISSUE TITLE
Trouble with config file?

### ISSUE THREAD

**Issue by regix1** [RaulH22/BetterInvisibility-SpigotPlugin#1]
Here's the console error I'm getting.
[https://pastebin.com/5kSnZdHx](https://pastebin.com/5kSnZdHx)

Here's the config file.
[https://pastebin.com/7VtSbrqj](https://pastebin.com/7VtSbrqj)

I only changed like one thing from false to true and added worlds. Not sure why it's throwing errors.

**Comment by RaulH22** [comment]
Fixed, thanks for report <3
