### ISSUE TITLE
Helmets appearing and no other armor (BUG)

### ISSUE THREAD

**Issue by regix1** [RaulH22/BetterInvisibility-SpigotPlugin#2]
![alt text](https://i.ibb.co/g4TFR1P/Screenshot-2021-03-19-002940.png)

Seems like after throwing a splash potion of invisibility on mobs, there helmet will come back after a few seconds and the rest of the armor wont.

**Comment by RaulH22** [comment]
I need to find out how to solve this, I think it happens when the zombie gets sun damage and the helmet protects.
Thanks for report <3

**Comment by RaulH22** [comment]
Now its solved 👍🏽
